fix assigning current axes to artist (lines) whose previous axes was destroyed (by closing widget)
Fixes this error if re-openning plotter after closing it.
ValueError: Can not reset the axes. You are probably trying to re-use an artist in more than one Axes which is not supported

Also, remove second toolbar and use qt made one